config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to:'home#index'

  get 'rooms/index'

  get 'rooms/new'

  post 'rooms/create'

  get 'rooms/join_room/:sessionId' => 'rooms#join_room' ,as: :join

  get 'users/index'

  post 'archives/start/:sessionId' => "archives#start"

  post 'archives/stop/:archiveID' => 'archives#stop'
  get 'archives/view/:archiveID' => 'archives#view'

  get 'home/index'
  get 'home/get_session_token/:sessionId' => 'home#get_session_token'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/room.rb
class Room < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!
  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def start
    archive = OP.opentok.archives.create params[:sessionId],{
      :name => "New Record",
      :has_video => true,
      :has_audio => true,
      :output_mode => :composed
    } rescue nil
    render :json => {:message => :ok}
  end

  def stop
    archive = OP.opentok.archives.find params[:archiveID]
    Rails.logger.info"AAAAAAAAAAAAAAA #{archive.id}"
    OP.opentok.archives.stop_by_id params[:archiveID] rescue nil
    render json: {"Message": "Stopped"}
  end

  def view
    archive = OP.opentok.archives.find(params[:archiveID])
    render :json => {:message => :opentok}
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def get_session_token
    @token = OP.opentok.generate_token params[:sessionId]
    render :json => {sessionId: @session_id, token: @token, apiKey: OP_CONFIG['API_KEY']}
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create

    session = OP.opentok.create_session(:media_mode => :routed) # auto record :archive_mode => :always
    session_id = session.session_id
    _room_params = room_params.merge!(:sessionId => session_id)
    @room = Room.new(_room_params)
    if @room.save
      redirect_to rooms_index_path, notice: "Create Room successful!"
    else
      render :new

    end

  end

  def start
  end

  def stop
  end

  def join_room
    @sessionId = params[:sessionId]
  end

  private
  def room_params
    params.require(:room).permit(:name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/archives/start.html.erb
<h1>Archives#start</h1>
<p>Find me in app/views/archives/start.html.erb</p>

app/views/archives/stop.html.erb
<h1>Archives#stop</h1>
<p>Find me in app/views/archives/stop.html.erb</p>

app/views/home/index.html.erb
<h1>Welcome to OpenTok</h1>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Opentok</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li role="presentation" class="<%= controller_name == 'home' ? 'active' : '' %>"><%= link_to"Home",home_index_path %></li>
        <li role="presentation" class="<%= controller_name == 'users' ? 'active' : '' %>"><%= link_to"User", users_index_path %></li>
        <li role="presentation" class="<%= controller_name == 'rooms' ? 'active' : '' %>"><%= link_to"Room", rooms_index_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="#"><span class="glyphicon glyphicon-user"></span> <%= current_user.email %></a></li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete  do  %>
                Logout <span class="glyphicon glyphicon-log-in"></span>
            <% end -%>
          </li>
        <% else %>
          <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <% end -%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OpenTok</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application" %>
  <script src="https://static.opentok.com/webrtc/v2.2/js/opentok.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/menu"%>
<%= yield %>

</body>
</html>

app/views/rooms/_room.html.erb
<tr>
  <td><%= room.name %></td>
  <td><%= room.sessionId %></td>
  <td><%= room.created_at.strftime('%y-%m-%d') %></td>
  <td><%= link_to"Join",join_path(room.sessionId) %></td>
</tr>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/index.html.erb
<h1>List Room</h1>
<table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>SessionId</th>
        <th>Created at</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    <%= render @rooms %>
    </tbody>
  </table>
<%= link_to"Create new Room ", rooms_new_path %>

app/views/rooms/join_room.html.erb
<div style="height:90%">
  <div id="videos">
      <div id="subscriber"></div>
      <div id="publisher"></div>
  </div>
  <div id="buttonholder">
    <div id="buttons">
        <button type="button" id="start" onClick="javascript:startArchive()" class="btn btn-danger">Start Recording</button>
        <button type="button" id="stop" onClick="javascript:stopArchive()" class="btn btn-danger">Stop Recording</button>
        <button type="button" id="view" onClick="javascript:viewArchive()" class="btn btn-danger" disabled>View Archive</button>
    </div>
  </div>
</div>
<% %w(sampleconfig.js opentok_app.js).each do |file| %>
  <%= javascript_include_tag file %>
<% end -%>

<script type="text/javascript">
var archiveID;
var sessionId = "<%= @sessionId %>";

$(document).ready(function(){

  archiveID = null;

  getApiAndToken();

  $('#stop').hide();

  $("#start").click(function(){
    startArchive();
  })
  $("#stop").click(function(){
    stopArchive();
  })
  $("#view").click(function(){
    viewArchive();
  })
});


  //Declare variable
function getApiAndToken() {
    console.log(sessionId);
    // make an Ajax Request to get the apiKey, sessionId and token from the server
    $.get(SAMPLE_SERVER_BASE_URL + '/home/get_session_token/'+ sessionId, function(data) {
        console.log(data['token']);
        apiKey = data['apiKey'];
        sessionId = sessionId;
        token = data['token'];

        initializeSession();
    });

}


function initializeSession() {
    // Initialize Session Object
    var session = OT.initSession(apiKey, sessionId);

    // Subscribe to a newly created stream
    session.on('streamCreated', function(event) {
        session.subscribe(event.stream, 'subscriber', {
            insertMode: 'append',
            width: '100%',
            height: '100%'
        });
    });
    // Handler for sessionDisconnected event
    session.on('sessionDisconnected', function(event) {
        console.log('You were disconnected from the session.', event.reason);
    });

    // Connect to the Session
    session.connect(token, function(error) {
        // If the connection is successful, initialize a publisher and publish to the session
        if (!error) {
            var publisher = OT.initPublisher('publisher', {
                insertMode: 'append',
                width: '100%',
                height: '100%',
                name: "<%= current_user.email %>",
                style: {nameDisplayMode: 'on'}
            });

            session.publish(publisher);

        } else {
            console.log('There was an error connecting to the session:', error.code, error.message);
        }

    });

    // Handler for ArchiveStarted Event
    session.on('archiveStarted', function(event){
        archiveID = event.id;
    })


}
//Function start record
function startArchive() {
    // Make ajax to request url start recording
    $.post(SAMPLE_SERVER_BASE_URL + "/archives/start/" + sessionId);
    $("#start").hide();
    $("#stop").show();

}
//Function stop record
function stopArchive() {
    console.log(archiveID);
    $.post(SAMPLE_SERVER_BASE_URL + "/archives/stop/" + archiveID);
    $("#start").show();
    $("#stop").hide();
    $("#view").prop('disabled',false);
}

//View record
function viewArchive() {
    window.open(SAMPLE_SERVER_BASE_URL + "/archives/view/" + archiveID);
    $("#view").prop('disabled',true);
}

</script>

app/views/rooms/new.html.erb
<%= form_for @room , url: rooms_create_path ,method: :post do |f| %>
  <div class="form-group">
    <%= f.label :name, "Room Name" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
<% end -%>

app/views/users/index.html.erb
<h1>User Profile</h1>